### PR TITLE
move some work into independent jobs

### PR DESCRIPTION
**Pull request by ImpleLee**
1. Sometimes "Download ColdClear" takes a long time on Mac OS where getting a response from `api.github.com` seems to be the slowest step. Now they have all been moved to Ubuntu, so we don't suffer from poor network conditions on Mac OS.
2. All `lua getVersion.lua` have been moved to Ubuntu, so there is no need to install lua repeatedly on each platform.

### CODE REVIEW

**Comment by ImpleLee** [comment]
Wait I forgot to change `release.yml`.

**Comment by ImpleLee** [comment]
It is too bothering to update `release.yml`...  I think this PR is ready for merge, and `release.yml` can be updated later since this PR didn't change any logic.

**Comment by ImpleLee** [comment]
`Squash and merge` option is the best for this pr I think.

**Comment by Trebor-Huang** [comment]
Oh so that's the problem. Probably GitHub doesn't host that many Mac machines, so they easily run out of API counts.

**Comment by Trebor-Huang** [comment]
It's not the network though. GitHub explicitly rejected our request because the same IP issued too many requests.

**Comment by ImpleLee** [comment]
What makes me curious is why the CI on Mac OS simply just can't get the result so they are forced to repeat the request once and once again until they run out of API counts...

**Comment by ImpleLee** [comment]
Now `release.yml` is also updated.

**Pull request merged**
