### PR TITLE
Vietnamese Zictionary update [ONLY MERGE AFTER MERGING #926]

### PR DESCRIPTION
**Pull request by SweetSea-ButImNotSweet**
Just an small update of Vietnamese Zictionary, not much at all, just tweaking words

You can consider it as extend PR for #903 (closed #914 due to my mistakes)
I made this PR after listening to some feedbacks

### CODE REVIEW

**Comment by SweetSea-ButImNotSweet** [comment]
READY to merge...

**Comment by SweetSea-ButImNotSweet** [comment]
DONE! @ShardNguyen I hope this time the file is cleaner and easy to view ;-;

**Comment by MrZ626** [comment]
waiting you for remove the "draft" state, I cannot press merge button

**Comment by SweetSea-ButImNotSweet** [comment]
> waiting you remove the "draft" state, or I cannot press merge button

Lmao #926 was not finished yet!!!

**Pull request merged**
