### PR TITLE
[DUPLICATED] Vietnamese translation (unfinished, not the Shard one, need reading proof)

### PR DESCRIPTION
**Pull request by SweetSea-ButImNotSweet**
Okay. Shard had quickly fork and made a draft PR before I did. And because I need reading proof too. So I decided to created one here. Hope everyone can help me

Note: 
1) Shard used my translation as the start base when I used... nothing. Yes, nothing. I also checked his translation in the past (Tetra Legends and also jstris). When he made a pull request (#835), I noticed and downloaded and use his translation as the base to compare and edit my tl too

2) My translation and Shard's one have some different and confusions. My style is trying to make sure that everyone will understand, even a beginner, (and with little jokes), that why some strings I decided to rewrite/use another word to describe. Meanwhile Shard's style is different.

3) I can't guarantee that in the next version (0.17.10 or 0.17.11), MrZ will use my or Shard's translation, or using both. It's depends so much things, and, you can't blame me or Shard if Shard's tl or my one is using. Okay? (just to make sure, and **DO NOT** ask me **A SILLY QUESTION LIKE: "WHO ASKED?"**)

P/s: edited to add the 4th note

4) The file lang_vi0.lua is the Shard's translation. But this file is not connected anywhere in the game. I will remove that file when my translation is done. Thanks

### CODE REVIEW

**Comment by SweetSea-ButImNotSweet** [comment]
> there are basically no toxic people on GitHub, we're all just programmers trying to create stuff, no one's gonna say silly things like "who asked"

image

Translation: 
Lemon: F/S: Sea is working with Shard (in translating)
Aleeysa: No one asked
Shard: Shard's file is very different
Almost things are done

**Comment by SweetSea-ButImNotSweet** [comment]
> there are basically no toxic people on GitHub, we're all just programmers trying to create stuff, no one's gonna say silly things like "who asked"

I just sent you an image which in a server that I have been banned so long (thanks Lemon)
Aleeysa, she is a mod but ||**very** toxic||, as I note "Do not ask a silly question like: "Who asked?"" with a reason: I don't want to get toxic here

**Review by ShardNguyen — COMMENTED** [review]
Line 1034: Pr-ing your name in a tip doesn't sound like a good translation to me

**Comment by SweetSea-ButImNotSweet** [comment]
> I agree with Shard on this one. I don't even do that in my Indonesian translation.

Removed

**Comment by SweetSea-ButImNotSweet** [comment]
> Line 1034: Pr-ing your name in a tip doesn't sound like a good idea to me

Line 1010 (in your translation): Recently the undersea cable is often broken, VNPT has tried to change the route. Please fix this one in your tl
image

**Comment by SweetSea-ButImNotSweet** [comment]
I want to tell you for a bit
image

LOVE is a 2D engine, not a game builder; this is the fact you may know (if you don't know, please go ahead to love2d.org).
Anyway, I use ``ĐƯỢC XÂY DỰNG BẰNG ENGINE LOVE`` while Shard use ``ĐƯỢC XÂY DỰNG VỚI LOVE``. Any idea?

**Comment by ShardNguyen** [comment]
> > Line 1034: Pr-ing your name in a tip doesn't sound like a good idea to me
> 
> Line 1010 (in your translation): Recently the undersea cable is often broken, VNPT has tried to change the route. Please fix this one in your tl
> image

It's a running gag whenever the Vietnamese's Internet is lagging, whether it is the server's fault or not

Look up "dit me VNPT" on Urban Dictionary for more information

**Comment by ShardNguyen** [comment]
> I want to tell you for a bit
> image
> 
> LOVE is a 2D engine, not a game builder; this is the fact you may know (if you don't know, please go ahead to love2d.org).
> Anyway, I use ``ĐƯỢC XÂY DỰNG BẰNG ENGINE LOVE`` while Shard use ``ĐƯỢC XÂY DỰNG VỚI LOVE``. Any idea?

Yes, I already know that fact. And how is this affecting the meaning? It is also translated as "Made with LOVE"

**Comment by SweetSea-ButImNotSweet** [comment]
Last update before Tet
Wish everyone had a good time with your family at Lunar New Year

(I will start translating Zictionary in tommorrow, bye bye)

**Comment by SweetSea-ButImNotSweet** [comment]
Sahrd's translation is ready to go
I don't need to continue my work

This PR will be closed **forever**

**Comment by vyishere** [comment]
huhuhu hehe

**Comment by SweetSea-ButImNotSweet** [comment]
> huhuhu hehe

Do I need to close fully by limiting comments?
(Hey, can someone mark @vyishere 's comment as off-topic?)

**Comment by vyishere** [comment]
Try me

**Pull request closed without merging**
