### PR TITLE
Various CI changes

### PR DESCRIPTION
**Pull request by Trebor-Huang**
TODOS
- [ ] 保证模板和artifact文件权限正确
- [ ] merge `main`
- [ ]

### CODE REVIEW

**Comment by Trebor-Huang** [comment]
等下还得改release

**Comment by ImpleLee** [comment]
Consider merging `main` to avoid so many changes to `*.lua`?

**Comment by Trebor-Huang** [comment]
> Consider merging `main` to avoid so many changes to `*.lua`?

I merged once. I think we will merge again when the draft is ready.

**Comment by ImpleLee** [comment]
Consider rebasing this branch again onto `main`'s latest merge with `ci-cc-url-related`?

**Comment by Trebor-Huang** [comment]
oh so when you delete a branch the pr gets closed too

**Pull request closed without merging**
